CREATE VIEW [dbo].[UnitView]	
    WITH SCHEMABINDING	
	AS SELECT 
       ROW_NUMBER() OVER(ORDER BY [MeasuringInstrument].[Id]) as [Uid]    
       ,[MeasuringInstrument].[Id]
      ,[VerificationTool].[Name]
      ,[VerificationTool].[VerificationNumber]
      ,[VerificationTool].[FirsVerificationNumber]
      ,[VerificationTool].[MiVerificationNumber]
      ,[VerificationTool].[CertificateNumber]
      ,[VerificationTool].[CertificateDate]
      ,[VerificationTool].[ValidityCertificateDate]
      ,[VerificationTool].[Range] AS [VerificationTool_Range]
	  ,[VerificationTool].[Characteristic] AS [VerificationTool_Characteristic]
	  ,[VerificationTool].[Discharge] AS [VerificationTool_Discharge]
      ,[MeasuringInstrument].[FactoryNumber]
      ,[MeasuringInstrument].[InventoryNumber]
      ,[MeasuringInstrument].[RegistrationNumber]
      ,[MeasuringInstrument].[IssueDate]
      ,[MeasuringInstrument].[CommissioningDate] 
      ,[InstallationLocation].[Name] as [InstallationLocation_Name]
      ,[Manufacturer].[Name] as [Manufacturer_Name]
      ,[Ownership].[Name] as [Ownership_Name]
      ,[dbo].[TypeSi].Name as [TypeSi_Name]   
      ,[dbo].[TypeSi].[Designation] as [TypeSi_Designation],
      [LINKNNFIF]
      FROM [dbo].[MeasuringInstrument]
	LEFT JOIN [dbo].[VerificationTool] ON [VerificationTool].[FK_MeasuringInstrument]=[MeasuringInstrument].[Id]
    JOIN [dbo].[TypeSi] ON [TypeSi].[Id]=[MeasuringInstrument].[FK_TypeSi]
    LEFT JOIN [dbo].[InstallationLocation] ON [InstallationLocation].[Id]=[MeasuringInstrument].[FK_InstallationLocation]    
    LEFT JOIN [dbo].[Organization] [Manufacturer]ON [Manufacturer].[Id]=[MeasuringInstrument].[FK_Manufacturer]
    LEFT JOIN [dbo].[Organization] [Ownership]ON [Manufacturer].[Id]=[MeasuringInstrument].[FK_Ownership]   
    GO

